### PR TITLE
Add issue templates

### PR DESCRIPTION
**Pull request by ryanleh**
This PR adds issue templates for bugs and feature requests.

### CODE REVIEW

**Comment by chester-leung** [comment]
Should we encourage people to use issue templates by[ not enabling blank issues by default](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser)?

"You can customize the issue template chooser that people see when creating a new issue in your repository by adding a config.yml file to the .github/ISSUE_TEMPLATE folder.

You can encourage contributors to use issue templates by setting blank_issues_enabled to false. If you set blank_issues_enabled to true, people will have the option to open a blank issue."

**Comment by wzheng** [comment]
If we disable blank issues, then we'd have to enable more templates than these. For example, some people create Github issues for setup problems, which are not bugs or feature requests. I think we should have at least another "Support" template. What do you think, @octaviansima?

**Comment by octaviansima** [comment]
I think we should keep blank issues for the case when an issue does not match a certain template, rather than create templates for all those various scenarios.

**Comment by ryanleh** [comment]
Ok, so is there anything left to do on this then?

**Comment by wzheng** [comment]
I agree with Octavian on enabling blank issues, though I think it would be nice to add a "Support" template?

**Comment by ryanleh** [comment]
Ok, I added a support template. Let me know if this is what you meant.

**Comment by chester-leung** [comment]
Will the support template now be the default template when opening an issue? Or how will that work?

**Comment by ryanleh** [comment]
So I'm not sure how to test this but, going off of this example [here](https://github.com/arkworks-rs/poly-commit), I believe users will choose one of them when they open an issue.

**Comment by chester-leung** [comment]
Ok this looks good then!

**Review by chester-leung — APPROVED** [review]

**Comment by ryanleh** [comment]
Ok, everything looks like it's working as intended! 🎉

**Pull request merged**
